(() => {
  const cfg = window.WPH_ACADEMY_PHASE3 || {categories:[],coding:[],mockPrompts:[]};
  const modules = window.WPH_ACADEMY_MODULES || [];
  const PROGRESS_KEY='wphAcademyProgressV1', READINESS_KEY='wphAcademyReadinessV1', QUIZ_KEY='wphAcademyQuizV1', CODING_KEY='wphAcademyCodingV1', PRACTICE_KEY='wphAcademyPracticeV1', REVIEW_KEY='wphAcademySpacedReviewV1';
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const readiness=read(READINESS_KEY,{}), quiz=read(QUIZ_KEY,{}), coding=read(CODING_KEY,{}), practice=read(PRACTICE_KEY,{}), reviews=read(REVIEW_KEY,{});
  const currentProgress=()=>read(PROGRESS_KEY,{});
  const statusFor=id=>currentProgress()[id]||'not-started';
  const quizScore=id=>typeof quiz[id]==='number'?quiz[id]:(quiz[id]?.score??null);
  const moduleScore=id=>{const s=statusFor(id),base=s==='mastered'?100:s==='learning'?55:20,q=quizScore(id);return q===null?base:Math.round((base+q)/2)};
  const categoryScore=cat=>Math.round(cat.modules.reduce((sum,id)=>sum+moduleScore(id),0)/Math.max(cat.modules.length,1));
  const weakModules=()=>modules.map(m=>({m,score:moduleScore(m.id)})).sort((a,b)=>a.score-b.score);
  const addDays=(days)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};

  function renderReadiness(){const host=document.getElementById('readiness-grid');if(!host)return;host.replaceChildren();cfg.categories.forEach(cat=>{const score=categoryScore(cat);readiness[cat.key]=score;const card=document.createElement('article');card.className='academy-readiness-card';const row=document.createElement('div');row.className='academy-readiness-row';const h=document.createElement('h3');h.textContent=cat.label;const n=document.createElement('strong');n.textContent=`${score}%`;row.append(h,n);const track=document.createElement('div');track.className='academy-readiness-track';const bar=document.createElement('span');bar.style.width=`${score}%`;track.appendChild(bar);const p=document.createElement('p');p.textContent=score>=80?'Interview-ready signal':score>=60?'Developing — keep practicing':'Priority practice area';card.append(row,track,p);host.appendChild(card)});write(READINESS_KEY,readiness)}

  function dailyPlan(){const today=new Date().toISOString().slice(0,10);if(practice.date===today&&Array.isArray(practice.modules))return practice.modules;const picks=weakModules().slice(0,3).map(x=>x.m.id);practice.date=today;practice.modules=picks;write(PRACTICE_KEY,practice);return picks}
  function renderPractice(){const host=document.getElementById('practice-today-list');if(!host)return;host.replaceChildren();dailyPlan().forEach((id,i)=>{const m=modules.find(x=>x.id===id);if(!m)return;const li=document.createElement('li');li.innerHTML=`<strong>${i+1}. ${String(id).padStart(2,'0')} — ${m.title}</strong><span>${m.outcome}</span>`;host.appendChild(li)});const codingHost=document.getElementById('practice-coding'),next=cfg.coding.find(c=>!coding[c.id])||cfg.coding[0];if(codingHost&&next)codingHost.textContent=`Coding: ${next.kind} — ${next.title}`}

  function renderReviews(){const host=document.getElementById('spaced-review-list');if(!host)return;host.replaceChildren();const today=new Date().toISOString().slice(0,10);const due=Object.entries(reviews).filter(([,v])=>v.due<=today).sort((a,b)=>a[1].due.localeCompare(b[1].due));if(!due.length){const p=document.createElement('p');p.className='academy-review-empty';p.textContent='Nothing due today. New review dates are scheduled when you score quiz answers.';host.appendChild(p);return}due.forEach(([id,v])=>{const m=modules.find(x=>x.id===Number(id));if(!m)return;const row=document.createElement('article');row.className='academy-review-row';const copy=document.createElement('div');copy.innerHTML=`<strong>${String(m.id).padStart(2,'0')} — ${m.title}</strong><span>Due ${v.due} · last result: ${v.lastResult}</span>`;const done=document.createElement('button');done.type='button';done.className='button';done.textContent='Reviewed';done.addEventListener('click',()=>{reviews[id]={due:addDays(3),lastResult:'reviewed'};write(REVIEW_KEY,reviews);renderReviews()});row.append(copy,done);host.appendChild(row)})}

  function renderCoding(){const host=document.getElementById('coding-challenges');if(!host)return;host.replaceChildren();cfg.coding.forEach(ch=>{const card=document.createElement('article');card.className='academy-coding-card';card.innerHTML=`<p class="eyebrow">${ch.kind}</p><h3>${ch.title}</h3><p>${ch.prompt}</p><p class="academy-coding-status">${coding[ch.id]?'✓ Practiced':'Not practiced'}</p>`;const hints=document.createElement('details'),hs=document.createElement('summary'),ul=document.createElement('ul');hs.textContent='Show hints';ch.hints.forEach(x=>{const li=document.createElement('li');li.textContent=x;ul.appendChild(li)});hints.append(hs,ul);const sol=document.createElement('details'),ss=document.createElement('summary'),pre=document.createElement('pre'),exp=document.createElement('p');ss.textContent='Show solution';pre.textContent=ch.solution;exp.textContent=ch.explain;sol.append(ss,pre,exp);const done=document.createElement('button');done.type='button';done.className='button';done.textContent='Mark practiced';done.addEventListener('click',()=>{coding[ch.id]={at:new Date().toISOString()};write(CODING_KEY,coding);renderCoding()});card.append(hints,sol,done);host.appendChild(card)})}

  function nextMock(){const host=document.getElementById('mock-question');if(host&&cfg.mockPrompts.length)host.textContent=cfg.mockPrompts[Math.floor(Math.random()*cfg.mockPrompts.length)]}
  function setupMock(){document.getElementById('new-mock-question')?.addEventListener('click',nextMock);nextMock();let timer=null,seconds=0;const display=document.getElementById('mock-timer'),start=document.getElementById('mock-start');start?.addEventListener('click',()=>{if(timer){clearInterval(timer);timer=null;start.textContent='Start timer';return}seconds=0;start.textContent='Stop timer';timer=setInterval(()=>{seconds++;if(display)display.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000)})}

  function saveQuiz(id,score,result){const current=quizScore(id)??50;quiz[id]={score:Math.round((current+score)/2),updatedAt:new Date().toISOString()};reviews[id]={due:addDays(result==='knew'?7:1),lastResult:result};write(QUIZ_KEY,quiz);write(REVIEW_KEY,reviews);renderReadiness();renderReviews()}
  function augmentQuiz(){const host=document.getElementById('dialog-quiz');if(!host)return;const observer=new MutationObserver(()=>{const id=Number((document.getElementById('dialog-number')?.textContent||'').replace(/\D/g,''));if(!id)return;host.querySelectorAll('.academy-quiz-item').forEach(item=>{if(item.querySelector('.academy-quiz-score'))return;const box=document.createElement('div');box.className='academy-quiz-score';const good=document.createElement('button'),weak=document.createElement('button');good.type=weak.type='button';good.textContent='I knew this';weak.textContent='Needs review';good.addEventListener('click',()=>saveQuiz(id,100,'knew'));weak.addEventListener('click',()=>saveQuiz(id,20,'needs review'));box.append(good,weak);item.appendChild(box)})});observer.observe(host,{childList:true,subtree:true})}

  document.addEventListener('DOMContentLoaded',()=>{renderReadiness();renderPractice();renderReviews();renderCoding();setupMock();augmentQuiz();document.getElementById('refresh-practice')?.addEventListener('click',()=>{delete practice.date;delete practice.modules;write(PRACTICE_KEY,practice);renderPractice()});const grid=document.getElementById('academy-module-grid');if(grid)new MutationObserver(()=>renderReadiness()).observe(grid,{childList:true})});
})();